name: Automate Preprocessing

on:
  push:
    branches:
      - main  # Trigger jalan setiap kali ada push ke branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_AnnisaZalfa.py

    - name: Upload Processed Data
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset
        path: HealthRisk_processed.csv  # Nama file hasil output script Anda
